server:
  port: 8080
  servlet:
    context-path: /training
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/TOMS_DB"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

gg:
  sheet:
    id: 15HW7AzD_nitLsS7UhdbuZaBgWMBvdbTRjz7fAzEwcCs
    range: User!A1:H