server:
  port: 8080
  servlet:
    context-path: /training
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/toms_db"
    username: root
    password: 12345689

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    logging:
      level:
        org.springframework.web.client.RestTemplate: DEBUG
        ut.edu.com.trainingonboardingmanagementsystem: DEBUG



gg:
  sheet:
    api-url: https://script.google.com/macros/s/AKfycbxOtStn3U3-MlO6R13wxb8Xbkw3_1BunZNH4a3YZlFfEvwdrbw2A8F4D55rBAjpEKp9/exec